### ISSUE TITLE
environment problem

### ISSUE THREAD

**Issue by AlexChenChenChen** [kaichen-z/manydepth2#1]
Execute the conda env create -f environment.yaml, it appears some problems of the packages version. I wonder if it is the right environment.yaml file? Or am i install in a wrong way?

Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 1.2.0 Requires-Python >=3.9; 1.2.1 Requires-Python >=3.9; 1.2.1rc1 Requires-Python >=3.9; 1.3.0 Requires-Python >=3.9; 4.6.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement diff-gaussian-rasterization==0.0.0 (from versions: none)
ERROR: No matching distribution found for diff-gaussian-rasterization==0.0.0
failed

CondaEnvException: Pip failed

**Comment by kaichen-z** [comment]
Thank you for your feedback. I’ve updated the ```environment.yaml```. Please let me know if you have any further questions. If not, I’ll go ahead and close this issue. By the way, Cuda  11.8 is used in our GPU.

**Comment by AlexChenChenChen** [comment]
Thank you so much for your patience, The problem has been solved successfully!
