### ISSUE TITLE
Solution of synthetic ref images without interference from dynamic object

### ISSUE THREAD

**Issue by Qianqian3764** [kaichen-z/Manydepth2#2]
thanks for your excellent job!

I have a question about synthetic ref images：`new_static_reference = ref_image*(~seg_ref) + static_reference_dyn*seg_ref`
However, I think this is still the original reference image, no changed, because the reconstruction of the dynamic object in the reference image is obtained using optical flow.
In Dynamic depth(2022 ECCV), the reconstruction of the dynamic target in the reference image is obtained by using the depth and pose, that is, the position of the target in the target image under the assumption of static situation. The position of the dynamic target is changed in the obtained synthetic ref image.

**Comment by kaichen-z** [comment]
Dear Qianqian,

Thank you very much for your detailed review. You are correct, and we mistakenly uploaded the wrong version of our code. Please find the updated version.

**Comment by kaichen-z** [comment]
Please let me know if there are any further issues. If not, we will proceed to close this comment.

**Comment by Asuna88** [comment]
thanks for your excellent job!

I also feel that
new_static_reference = ref_image * (~seg_ref) + static_reference_dyn * seg_ref
has some issues.

I noticed that Qianqian3764 raised the same question, but I didn’t see your updated code.
May I ask if you have fixed this issue?
Where can I find the updated version? I'm sorry I couldn’t locate it. Thank you.

**Comment by kaichen-z** [comment]
The previous error did not originate from the equation itself, but rather from the function def compute_dynamic_flow(self, lookup_pose, _flow, depth, _K, _invK, current_image, lookup_images). In this update, we have aligned the flow computation in the code with the equation presented in our paper.

**Comment by Asuna88** [comment]
Thank you very much for your work.

In your previous message, you mentioned:
“Thank you very much for your detailed review. You are correct, and we mistakenly uploaded the wrong version of our code. Please find the updated version.”

However, as of March 9, 2026, when I checked your GitHub repository, the latest visible update still appears to be from two years ago. Therefore, I am wondering where the corrected or updated code can be obtained.

I assume that the modification may involve the function **compute_static_reference_dyn**, but I have not been able to find the updated code files or any related commit logs in the repository.

Would it be possible for you to share the updated version of the function **compute_static_reference_dyn**   or the **multi_flow_hrnet_encoder00.py** file?

Thank you very much for your time and assistance.

**Comment by Asuna88** [comment]
> The previous error did not originate from the equation itself, but rather from the function def compute_dynamic_flow(self, lookup_pose, _flow, depth, _K, _invK, current_image, lookup_images). In this update, we have aligned the flow computation in the code with the equation presented in our paper.

Dear Kaichen,

Thank you for your previous responses regarding the new_static_reference and static_reference_dyn computation.

Even if the equation itself is correct, I am now curious about the update you mentioned for the computation process. Could you kindly clarify what exactly was modified, and where I can access the updated code or multi_flow_hrnet_encoder00.py file? 

Currently, the version I can see on GitHub is still “uploaded 2 years ago,” and the function
`
def compute_dynamic_flow(self, lookup_pose, _flow, depth, _K, _invK, current_image, lookup_images)`

appears unchanged.

I would greatly appreciate your guidance on this. Thank you very much for your time and help.

**Comment by Asuna88** [comment]
> > The previous error did not originate from the equation itself, but rather from the function def compute_dynamic_flow(self, lookup_pose, _flow, depth, _K, _invK, current_image, lookup_images). In this update, we have aligned the flow computation in the code with the equation presented in our paper.
> 
> Dear Kaichen,
> 
> Thank you for your previous responses regarding the new_static_reference and static_reference_dyn computation.
> 
> Even if the equation itself is correct, I am now curious about the update you mentioned for the computation process. Could you kindly clarify what exactly was modified, and where I can access the updated code or multi_flow_hrnet_encoder00.py file?
> 
> Currently, the version I can see on GitHub is still “uploaded 2 years ago,” and the function ` def compute_dynamic_flow(self, lookup_pose, _flow, depth, _K, _invK, current_image, lookup_images)`
> 
> appears unchanged.
> 
> I would greatly appreciate your guidance on this. Thank you very much for your time and help.






Hello, Kaichen. Would it be possible for you to continue with the explanation when you have time? This question is very important to me, as I believe that once I fully understand it, I will grasp the essence of your paper.

Thank you for your help, and I look forward to your response.

**Comment by Asuna88** [comment]
> Thank you very much for your work.
> 
> In your previous message, you mentioned: “Thank you very much for your detailed review. You are correct, and we mistakenly uploaded the wrong version of our code. Please find the updated version.”
> 
> However, as of March 9, 2026, when I checked your GitHub repository, the latest visible update still appears to be from two years ago. Therefore, I am wondering where the corrected or updated code can be obtained.
> 
> I assume that the modification may involve the function **compute_static_reference_dyn**, but I have not been able to find the updated code files or any related commit logs in the repository.
> 
> Would it be possible for you to share the updated version of the function **compute_static_reference_dyn** or the **multi_flow_hrnet_encoder00.py** file?
> 
> Thank you very much for your time and assistance.





Hello, Kaichen. Would it be possible for you to continue with the explanation when you have time? This question is very important to me, as I believe that once I fully understand it, I will grasp the essence of your paper.

Thank you for your help, and I look forward to your response.
